current_index: 0
pic_org_path: D:\work\ubilink\AIVideoIdentification\firstVersionSource\20210415imgfirstdealwith
pic_save_path: D:\work\ubilink\AIVideoIdentification\firstVersionSource\20210416imgseconddealwith
